import type { Club, Application, AdminApplicant, AssessmentQuestion } from "./types";

export const clubs: Club[] = [
  {
    id: "1",
    name: "星韵合唱团",
    category: "文艺",
    tags: ["音乐", "表演", "合唱"],
    description: "我们是一支充满热情的校园合唱团，致力于用音乐连接心灵。每周定期排练，参加各类演出和比赛，感受集体音乐的魅力。",
    activities: ["周末排练", "校园音乐节", "社团联合演出", "外出比赛"],
    atmosphere: "温馨和谐，积极向上",
    hoursPerWeek: 4,
    beginnerFriendly: 4,
    isRecruiting: true,
    recruitmentDirections: ["女高音", "男低音", "钢琴伴奏"],
    customQuestions: ["请介绍你的音乐背景", "你最喜欢的歌曲类型是什么"],
    matchKeywords: ["创意表达", "艺术", "团队协作", "音乐", "表演"],
    memberCount: 56,
    coverImage: "https://picsum.photos/seed/1/800/400",
    reviews: [
      { id: "r1", author: "小雅", avatar: "🎵", content: "加入合唱团是我大学最棒的决定！大家一起唱歌的感觉太美妙了。", rating: 5, date: "2024-01-15" },
      { id: "r2", author: "阿明", avatar: "🎶", content: "每周排练压力不大，老师很有耐心，哪怕零基础也能快速融入。", rating: 5, date: "2024-02-08" },
      { id: "r3", author: "晴晴", avatar: "🎤", content: "参加了校园音乐节表演，站在舞台上的感觉真的很特别！", rating: 4, date: "2024-03-01" },
    ],
    timeline: [
      { date: "2024-09-01", event: "秋季纳新", description: "开始招募新成员" },
      { date: "2024-10-15", event: "新生汇报演出", description: "新成员第一次正式登台" },
      { date: "2024-12-20", event: "迎新晚会演出", description: "年度最大规模演出" },
    ],
  },
  {
    id: "2",
    name: "光影摄影社",
    category: "艺术",
    tags: ["摄影", "创作", "视觉"],
    description: "用镜头记录校园最美的瞬间。我们探索摄影技术与艺术表达，从人像到风景，从胶片到数码，记录生活中的每一帧美好。",
    activities: ["摄影采风", "作品展览", "技术分享会", "校园纪实项目"],
    atmosphere: "自由创意，互相学习",
    hoursPerWeek: 3,
    beginnerFriendly: 5,
    isRecruiting: true,
    recruitmentDirections: ["风光摄影", "人像摄影", "后期修图"],
    customQuestions: ["你用什么相机设备", "分享一张你拍的照片"],
    matchKeywords: ["创意表达", "艺术", "视觉", "技术探索"],
    memberCount: 42,
    coverImage: "https://picsum.photos/seed/2/800/400",
    reviews: [
      { id: "r1", author: "小鱼", avatar: "📷", content: "即使是手机党也能在这里学到很多构图和光影知识，氛围超好！", rating: 5, date: "2024-02-10" },
      { id: "r2", author: "阿杰", avatar: "🖼️", content: "每次采风都会发现校园里好多被忽视的美景，眼界大开。", rating: 5, date: "2024-03-05" },
    ],
    timeline: [
      { date: "2024-09-10", event: "秋季纳新", description: "新成员加入" },
      { date: "2024-11-01", event: "作品展览", description: "在图书馆展出成员摄影作品" },
    ],
  },
  {
    id: "3",
    name: "墨韵书法社",
    category: "文化",
    tags: ["书法", "传统文化", "艺术"],
    description: "传承中华书法艺术，在墨香中感受传统文化的魅力。从楷书到行书，从笔法到章法，带你走进书法的世界。",
    activities: ["每周练习课", "作品展览", "文化讲座", "节日书法活动"],
    atmosphere: "静心沉稳，文化氛围浓厚",
    hoursPerWeek: 3,
    beginnerFriendly: 5,
    isRecruiting: true,
    recruitmentDirections: ["楷书组", "行书组", "篆刻组"],
    customQuestions: ["你有书法基础吗", "你对哪种书体最感兴趣"],
    matchKeywords: ["学术研究", "传统文化", "艺术", "创意表达"],
    memberCount: 38,
    coverImage: "https://picsum.photos/seed/3/800/400",
    reviews: [
      { id: "r1", author: "文轩", avatar: "🖌️", content: "在这里学书法让我静下心来，从浮躁到沉稳，收获很大。", rating: 5, date: "2024-01-20" },
    ],
    timeline: [
      { date: "2024-09-05", event: "秋季纳新", description: "招募热爱书法的新成员" },
      { date: "2025-01-20", event: "春节书法联欢", description: "社员共同书写春联" },
    ],
  },
  {
    id: "4",
    name: "风行跑步社",
    category: "运动",
    tags: ["跑步", "健身", "马拉松"],
    description: "用奔跑丈量校园，用汗水诠释青春。我们组织各类跑步活动，从晨跑到马拉松，让每一步都充满力量。",
    activities: ["每日晨跑", "路跑比赛", "健身讲座", "马拉松培训"],
    atmosphere: "积极阳光，充满活力",
    hoursPerWeek: 5,
    beginnerFriendly: 4,
    isRecruiting: true,
    recruitmentDirections: ["长跑组", "短跑组", "训练助教"],
    customQuestions: ["你目前的跑步水平如何", "你的运动目标是什么"],
    matchKeywords: ["运动健将", "健康生活", "挑战自我"],
    memberCount: 89,
    coverImage: "https://picsum.photos/seed/4/800/400",
    reviews: [
      { id: "r1", author: "小豪", avatar: "🏃", content: "刚入学不会跑步，现在半马都能完赛！感谢社团的系统训练。", rating: 5, date: "2024-03-12" },
      { id: "r2", author: "云峰", avatar: "👟", content: "早上和大家一起跑步，整天都精力充沛，强烈推荐！", rating: 5, date: "2024-02-20" },
    ],
    timeline: [
      { date: "2024-09-01", event: "新学期启动跑", description: "全员10公里迎新跑" },
      { date: "2024-11-10", event: "城市半马参赛", description: "组队参加城市马拉松" },
    ],
  },
  {
    id: "5",
    name: "篮球俱乐部",
    category: "运动",
    tags: ["篮球", "竞技", "团队"],
    description: "激情篮球，燃烧青春！我们是校园最活跃的篮球团体，组织训练、比赛和交流活动，欢迎所有热爱篮球的同学加入。",
    activities: ["每周训练", "校际联赛", "三对三赛事", "篮球夏令营"],
    atmosphere: "热血竞技，团队精神",
    hoursPerWeek: 6,
    beginnerFriendly: 3,
    isRecruiting: true,
    recruitmentDirections: ["控卫", "前锋", "中锋", "拉拉队"],
    customQuestions: ["你打篮球几年了", "你在球队中擅长什么位置"],
    matchKeywords: ["运动健将", "团队协作", "社交活力", "竞技"],
    memberCount: 75,
    coverImage: "https://picsum.photos/seed/5/800/400",
    reviews: [
      { id: "r1", author: "阿龙", avatar: "🏀", content: "每周训练强度适中，有专业教练指导，技术进步很快。", rating: 4, date: "2024-01-25" },
    ],
    timeline: [
      { date: "2024-09-15", event: "秋季联赛开幕", description: "校内篮球联赛正式开始" },
      { date: "2024-12-01", event: "冬季三对三", description: "举办全校三对三邀请赛" },
    ],
  },
  {
    id: "6",
    name: "羽毛球协会",
    category: "运动",
    tags: ["羽毛球", "休闲", "竞技"],
    description: "羽毛球是老少皆宜的运动，我们欢迎所有水平的同学。无论是休闲娱乐还是专业竞技，都能在这里找到属于你的位置。",
    activities: ["日常打球", "协会内赛", "校际比赛", "技术培训"],
    atmosphere: "友好包容，老少皆宜",
    hoursPerWeek: 4,
    beginnerFriendly: 5,
    isRecruiting: true,
    recruitmentDirections: ["技术组", "竞技组", "教学志愿者"],
    customQuestions: ["你的羽毛球技术水平如何", "你偏好单打还是双打"],
    matchKeywords: ["运动健将", "社交活力", "休闲"],
    memberCount: 63,
    coverImage: "https://picsum.photos/seed/6/800/400",
    reviews: [
      { id: "r1", author: "小蝶", avatar: "🏸", content: "每次打球都很开心，大家不管是高手还是新手都一起玩，氛围超棒！", rating: 5, date: "2024-02-14" },
    ],
    timeline: [
      { date: "2024-09-10", event: "新学期开放日", description: "免费体验打球" },
      { date: "2024-10-20", event: "校际邀请赛", description: "与兄弟院校切磋技艺" },
    ],
  },
  {
    id: "7",
    name: "青年志愿者协会",
    category: "公益",
    tags: ["志愿服务", "公益", "社会责任"],
    description: "传递爱心，服务社会。我们组织各类志愿服务活动，从支教到社区服务，让青年的力量为社会带来温暖和改变。",
    activities: ["周末支教", "社区服务", "公益宣传", "扶贫助困"],
    atmosphere: "温暖有爱，服务精神",
    hoursPerWeek: 4,
    beginnerFriendly: 5,
    isRecruiting: true,
    recruitmentDirections: ["活动策划", "教育支援", "宣传设计", "外联联络"],
    customQuestions: ["你做过哪些志愿服务", "你为什么想加入志愿者协会"],
    matchKeywords: ["公益服务", "社交活力", "团队协作", "社会责任"],
    memberCount: 112,
    coverImage: "https://picsum.photos/seed/7/800/400",
    reviews: [
      { id: "r1", author: "晨曦", avatar: "💝", content: "每次支教回来都很感动，孩子们的笑脸是最好的回报。", rating: 5, date: "2024-01-30" },
      { id: "r2", author: "海涛", avatar: "🤝", content: "认识了很多志同道合的朋友，一起做公益，特别有意义。", rating: 5, date: "2024-03-08" },
    ],
    timeline: [
      { date: "2024-09-01", event: "秋季纳新", description: "招募热心公益的新成员" },
      { date: "2024-10-01", event: "国庆公益行", description: "走进社区开展志愿服务" },
      { date: "2024-12-25", event: "圣诞爱心活动", description: "为孤儿院孩子送温暖" },
    ],
  },
  {
    id: "8",
    name: "绿色环保社",
    category: "公益",
    tags: ["环保", "可持续", "公益"],
    description: "守护绿色地球，从校园开始。我们通过宣传教育和实践活动，培养环保意识，推动可持续发展理念在校园落地。",
    activities: ["校园清洁活动", "环保主题讲座", "绿化种植", "废物回收"],
    atmosphere: "务实行动，绿色理念",
    hoursPerWeek: 3,
    beginnerFriendly: 5,
    isRecruiting: true,
    recruitmentDirections: ["活动组织", "宣传策划", "科研调研"],
    customQuestions: ["你对哪个环保议题最关注", "你有什么环保实践经验"],
    matchKeywords: ["公益服务", "学术研究", "社会责任"],
    memberCount: 47,
    coverImage: "https://picsum.photos/seed/8/800/400",
    reviews: [
      { id: "r1", author: "绿叶", avatar: "🌱", content: "在这里学到了很多环保知识，也真正把环保行动落到了实处。", rating: 4, date: "2024-02-25" },
    ],
    timeline: [
      { date: "2024-04-22", event: "地球日活动", description: "举办校园环保周系列活动" },
      { date: "2024-06-05", event: "环境日宣传", description: "公益宣传绿色生活理念" },
    ],
  },
  {
    id: "9",
    name: "模拟联合国协会",
    category: "学术",
    tags: ["国际关系", "辩论", "外交"],
    description: "模拟联合国是锻炼国际视野和辩论能力的绝佳平台。我们组织模拟联合国大会，让同学们扮演各国代表，讨论全球议题。",
    activities: ["模拟联大", "辩论培训", "国际时事讨论", "校际MUN比赛"],
    atmosphere: "严谨学术，国际视野",
    hoursPerWeek: 5,
    beginnerFriendly: 3,
    isRecruiting: true,
    recruitmentDirections: ["代表团成员", "学术委员会", "新闻组"],
    customQuestions: ["你对哪个国际议题最感兴趣", "你有MUN经历吗"],
    matchKeywords: ["学术研究", "社交活力", "技术探索", "国际视野"],
    memberCount: 58,
    coverImage: "https://picsum.photos/seed/9/800/400",
    reviews: [
      { id: "r1", author: "子悦", avatar: "🌍", content: "MUN训练了我的演讲和辩论能力，视野也开阔了很多。", rating: 5, date: "2024-03-15" },
    ],
    timeline: [
      { date: "2024-10-01", event: "新生培训营", description: "MUN基础知识培训" },
      { date: "2024-11-15", event: "校内模拟联合国", description: "举办全校MUN大会" },
    ],
  },
  {
    id: "10",
    name: "英语演讲社",
    category: "学术",
    tags: ["英语", "演讲", "辩论"],
    description: "用英语表达自我，展示思想的力量。我们提供专业的英语演讲和辩论训练，帮助同学们提升英语能力和公众表达技巧。",
    activities: ["演讲训练课", "英语辩论赛", "TED风格演讲", "口语角"],
    atmosphere: "开放自信，国际化氛围",
    hoursPerWeek: 4,
    beginnerFriendly: 4,
    isRecruiting: true,
    recruitmentDirections: ["演讲组", "辩论组", "口语训练志愿者"],
    customQuestions: ["你的英语水平如何（四六级/托福）", "你有公开演讲经验吗"],
    matchKeywords: ["学术研究", "社交活力", "创意表达"],
    memberCount: 44,
    coverImage: "https://picsum.photos/seed/10/800/400",
    reviews: [
      { id: "r1", author: "Emily", avatar: "🎙️", content: "在这里演讲技巧突飞猛进，还交到了很多英语好朋友！", rating: 5, date: "2024-02-18" },
    ],
    timeline: [
      { date: "2024-09-20", event: "新生演讲工作坊", description: "零基础演讲入门" },
      { date: "2024-12-10", event: "年度TED演讲夜", description: "成员精彩演讲展示" },
    ],
  },
  {
    id: "11",
    name: "编程极客社",
    category: "技术",
    tags: ["编程", "技术", "开发"],
    description: "探索代码的世界，用技术改变生活。我们涵盖Web开发、算法竞赛、人工智能等多个技术方向，为技术爱好者提供学习和实践的平台。",
    activities: ["技术分享会", "黑客马拉松", "算法竞赛培训", "开源项目"],
    atmosphere: "极客精神，技术驱动",
    hoursPerWeek: 6,
    beginnerFriendly: 3,
    isRecruiting: true,
    recruitmentDirections: ["前端开发", "后端开发", "算法竞赛", "AI方向"],
    customQuestions: ["你掌握哪些编程语言", "介绍你做过的一个项目"],
    matchKeywords: ["技术探索", "创新创业", "学术研究"],
    memberCount: 83,
    coverImage: "https://picsum.photos/seed/11/800/400",
    reviews: [
      { id: "r1", author: "码农阿飞", avatar: "💻", content: "这里大神很多，每次技术分享都能学到新东西，成长很快。", rating: 5, date: "2024-01-22" },
      { id: "r2", author: "小白鼠", avatar: "🖥️", content: "零基础加入，现在已经能独立做项目了！导师很耐心。", rating: 5, date: "2024-03-10" },
    ],
    timeline: [
      { date: "2024-09-15", event: "秋季纳新", description: "招募技术新血" },
      { date: "2024-10-20", event: "黑客马拉松", description: "48小时极限编程挑战" },
      { date: "2024-12-15", event: "年终项目展", description: "成员项目成果展示" },
    ],
  },
  {
    id: "12",
    name: "创新创业协会",
    category: "创业",
    tags: ["创业", "创新", "商业"],
    description: "激发创业热情，实现创业梦想。我们为有创业想法的同学提供资源、导师和平台，从商业计划书到实际项目落地，全程支持你的创业之旅。",
    activities: ["创业分享会", "商业计划大赛", "导师面对面", "创业实战项目"],
    atmosphere: "充满激情，勇于创新",
    hoursPerWeek: 5,
    beginnerFriendly: 4,
    isRecruiting: true,
    recruitmentDirections: ["产品策划", "商业运营", "技术开发", "市场推广"],
    customQuestions: ["你有什么创业想法", "你认为自己的核心优势是什么"],
    matchKeywords: ["创新创业", "技术探索", "社交活力"],
    memberCount: 69,
    coverImage: "https://picsum.photos/seed/12/800/400",
    reviews: [
      { id: "r1", author: "超级创客", avatar: "🚀", content: "在这里认识了很多优秀的创业伙伴，我们的项目已经获得了天使投资！", rating: 5, date: "2024-02-28" },
    ],
    timeline: [
      { date: "2024-09-25", event: "秋季路演", description: "创业项目路演大会" },
      { date: "2024-11-30", event: "商业计划大赛", description: "优秀项目获取孵化资源" },
    ],
  },
  {
    id: "13",
    name: "街舞嘻哈社",
    category: "文艺",
    tags: ["街舞", "嘻哈", "表演"],
    description: "释放能量，用舞步讲述故事！我们汇聚了各种街舞风格：Breaking、Popping、Locking、Waacking…不管是零基础还是老手，这里都有你的舞台。",
    activities: ["每周训练", "校内街舞大赛", "社团联合演出", "街舞workshop"],
    atmosphere: "自由奔放，青春活力",
    hoursPerWeek: 5,
    beginnerFriendly: 4,
    isRecruiting: true,
    recruitmentDirections: ["Breaking组", "Popping组", "综合组"],
    customQuestions: ["你有街舞基础吗", "你最喜欢哪种街舞风格"],
    matchKeywords: ["创意表达", "艺术", "社交活力", "表演"],
    memberCount: 61,
    coverImage: "https://picsum.photos/seed/13/800/400",
    reviews: [
      { id: "r1", author: "Funky凯", avatar: "🕺", content: "这里超自由，每个人都有自己的风格，不会强迫你跳什么。", rating: 5, date: "2024-02-05" },
    ],
    timeline: [
      { date: "2024-09-12", event: "秋季纳新", description: "公开课免费体验" },
      { date: "2024-11-25", event: "校园街舞大赛", description: "各组别争夺冠军" },
    ],
  },
  {
    id: "14",
    name: "辩论协会",
    category: "学术",
    tags: ["辩论", "逻辑", "演讲"],
    description: "思维的碰撞，语言的艺术。辩论协会致力于提升同学的逻辑思维、表达能力和批判性思考，通过激烈的辩论，磨砺思想的锋芒。",
    activities: ["辩论训练", "校内辩论赛", "友谊赛", "辩论讲座"],
    atmosphere: "严谨理性，思维锋利",
    hoursPerWeek: 4,
    beginnerFriendly: 3,
    isRecruiting: true,
    recruitmentDirections: ["正方辩手", "反方辩手", "赛务志愿者"],
    customQuestions: ["你对哪类辩题最感兴趣", "介绍一次你印象深刻的辩论经历"],
    matchKeywords: ["学术研究", "社交活力", "创意表达"],
    memberCount: 52,
    coverImage: "https://picsum.photos/seed/14/800/400",
    reviews: [
      { id: "r1", author: "论坛高手", avatar: "🗣️", content: "训练真的很系统，不只是说话快，更是教会我如何有逻辑地思考。", rating: 5, date: "2024-01-28" },
    ],
    timeline: [
      { date: "2024-09-22", event: "新生辩论营", description: "辩论基础技能培训" },
      { date: "2024-11-08", event: "校际辩论赛", description: "与全市高校同台竞技" },
    ],
  },
  {
    id: "15",
    name: "厨艺美食社",
    category: "文化",
    tags: ["烹饪", "美食", "生活"],
    description: "民以食为天，美食是最好的语言。我们探索各地美食文化，从家常菜到西式甜点，每周聚在一起动手做美食，分享美味的快乐。",
    activities: ["每周烹饪课", "美食文化节", "菜系探索活动", "节日特别美食"],
    atmosphere: "温馨热闹，共享美食",
    hoursPerWeek: 3,
    beginnerFriendly: 5,
    isRecruiting: true,
    recruitmentDirections: ["中餐组", "西点烘焙组", "饮品制作组"],
    customQuestions: ["你会做哪些菜", "你最想学什么厨艺"],
    matchKeywords: ["创意表达", "社交活力", "传统文化"],
    memberCount: 49,
    coverImage: "https://picsum.photos/seed/15/800/400",
    reviews: [
      { id: "r1", author: "吃货小爱", avatar: "🍳", content: "每次活动都能吃到超多好东西，而且大家都很友好！", rating: 5, date: "2024-03-02" },
    ],
    timeline: [
      { date: "2024-09-20", event: "开学美食节", description: "各地美食大汇聚" },
      { date: "2025-02-10", event: "新年年夜饭", description: "社员共享自制年夜饭" },
    ],
  },
  {
    id: "16",
    name: "电子竞技社",
    category: "技术",
    tags: ["电竞", "游戏", "竞技"],
    description: "电竞不是玩物丧志，而是追求卓越！我们以专业的态度对待游戏，组织各类校内外电竞赛事，培养团队协作和竞技精神。",
    activities: ["日常训练", "校内联赛", "跨校邀请赛", "电竞直播"],
    atmosphere: "竞技专业，热血激情",
    hoursPerWeek: 6,
    beginnerFriendly: 3,
    isRecruiting: true,
    recruitmentDirections: ["LOL组", "CS2组", "王者荣耀组", "赛事运营"],
    customQuestions: ["你玩什么游戏，段位如何", "你对电竞比赛有什么理解"],
    matchKeywords: ["技术探索", "团队协作", "竞技"],
    memberCount: 78,
    coverImage: "https://picsum.photos/seed/16/800/400",
    reviews: [
      { id: "r1", author: "电竞少年", avatar: "🎮", content: "在这里打比赛才明白什么叫真正的团队配合，游戏水平涨了一大截！", rating: 4, date: "2024-02-22" },
    ],
    timeline: [
      { date: "2024-09-18", event: "赛季开幕", description: "新学年联赛正式开始" },
      { date: "2024-12-08", event: "年度总决赛", description: "各项目总决赛" },
    ],
  },
  {
    id: "17",
    name: "瑜伽冥想社",
    category: "运动",
    tags: ["瑜伽", "冥想", "健康"],
    description: "在忙碌的大学生活中找到内心的平静。我们提供专业的瑜伽和冥想课程，帮助同学们舒缓压力、提升专注力，培养身心健康的生活方式。",
    activities: ["每日瑜伽课", "冥想工作坊", "户外正念体验", "压力管理讲座"],
    atmosphere: "安静舒适，身心平衡",
    hoursPerWeek: 3,
    beginnerFriendly: 5,
    isRecruiting: true,
    recruitmentDirections: ["瑜伽教学组", "冥想引导组", "活动策划组"],
    customQuestions: ["你有瑜伽或冥想经验吗", "你希望通过瑜伽获得什么"],
    matchKeywords: ["健康生活", "公益服务", "创意表达"],
    memberCount: 35,
    coverImage: "https://picsum.photos/seed/17/800/400",
    reviews: [
      { id: "r1", author: "静心姐", avatar: "🧘", content: "期末考前参加冥想课，效果超好，焦虑少了很多，推荐给每个同学！", rating: 5, date: "2024-01-08" },
    ],
    timeline: [
      { date: "2024-09-05", event: "新学期开放日", description: "免费体验瑜伽课" },
      { date: "2024-06-21", event: "夏至特别活动", description: "户外日出瑜伽" },
    ],
  },
  {
    id: "18",
    name: "天文观测协会",
    category: "学术",
    tags: ["天文", "科学", "观测"],
    description: "仰望星空，探索宇宙奥秘。我们拥有专业天文望远镜，定期组织观星活动，探讨天体物理，让对宇宙充满好奇的你在这里找到同伴。",
    activities: ["夜间观星", "天文摄影", "学术讲座", "流星雨观测"],
    atmosphere: "充满好奇，探索精神",
    hoursPerWeek: 3,
    beginnerFriendly: 4,
    isRecruiting: true,
    recruitmentDirections: ["观测组", "摄影组", "学术研究组"],
    customQuestions: ["你最感兴趣的天体是什么", "你有天文观测经验吗"],
    matchKeywords: ["学术研究", "技术探索", "创意表达"],
    memberCount: 30,
    coverImage: "https://picsum.photos/seed/18/800/400",
    reviews: [
      { id: "r1", author: "星空追寻者", avatar: "🔭", content: "第一次看到土星环的那一刻，真的被震撼了，推荐每个人都来体验！", rating: 5, date: "2024-03-18" },
    ],
    timeline: [
      { date: "2024-08-12", event: "英仙座流星雨", description: "夜间观测英仙座流星雨" },
      { date: "2024-11-18", event: "狮子座流星雨", description: "秋季流星雨联合观测" },
    ],
  },
  {
    id: "19",
    name: "动漫文化社",
    category: "文化",
    tags: ["动漫", "cosplay", "二次元"],
    description: "二次元也是我们的主场！我们聚集了热爱动漫、漫画、轻小说的同学，定期举办动漫展、Cosplay活动和同人创作分享，打造校园二次元文化圈。",
    activities: ["动漫展映", "Cosplay大赛", "同人创作", "声优讲座"],
    atmosphere: "活泼有趣，创意无限",
    hoursPerWeek: 3,
    beginnerFriendly: 5,
    isRecruiting: true,
    recruitmentDirections: ["绘画创作组", "Cosplay组", "活动策划组"],
    customQuestions: ["你最喜欢的动漫是什么", "你有绘画或制作Cos服装的经验吗"],
    matchKeywords: ["创意表达", "艺术", "社交活力"],
    memberCount: 91,
    coverImage: "https://picsum.photos/seed/19/800/400",
    reviews: [
      { id: "r1", author: "二次元战士", avatar: "🎌", content: "终于找到了志同道合的朋友！大家聊动漫超嗨，还能一起做手办。", rating: 5, date: "2024-02-12" },
    ],
    timeline: [
      { date: "2024-05-04", event: "动漫文化节", description: "校园最大规模动漫主题活动" },
      { date: "2024-10-30", event: "万圣节Cosplay", description: "主题Cosplay巡游" },
    ],
  },
  {
    id: "20",
    name: "国际交流协会",
    category: "文化",
    tags: ["国际交流", "语言", "文化"],
    description: "连接世界，从校园开始。我们促进中外学生之间的文化交流，组织语言交换、国际文化节和海外游学项目，让你不出国门也能体验国际化氛围。",
    activities: ["语言交换活动", "国际文化节", "留学经验分享", "海外游学"],
    atmosphere: "开放包容，国际视野",
    hoursPerWeek: 3,
    beginnerFriendly: 5,
    isRecruiting: true,
    recruitmentDirections: ["中外学生联络", "活动策划", "翻译志愿者"],
    customQuestions: ["你会哪些外语", "你有过跨文化交流经历吗"],
    matchKeywords: ["社交活力", "学术研究", "国际视野"],
    memberCount: 58,
    coverImage: "https://picsum.photos/seed/20/800/400",
    reviews: [
      { id: "r1", author: "环球旅行者", avatar: "🌏", content: "认识了很多来自不同国家的朋友，视野真的打开了！", rating: 5, date: "2024-03-20" },
    ],
    timeline: [
      { date: "2024-05-20", event: "国际文化节", description: "40+国家文化展示" },
      { date: "2024-12-01", event: "圣诞文化交流", description: "中外学生共迎圣诞" },
    ],
  },
];

export const assessmentQuestions: AssessmentQuestion[] = [
  {
    id: 1,
    question: "你最享受的课余活动是什么？",
    options: [
      { text: "绘画、音乐、写作等艺术创作", keywords: ["创意表达"] },
      { text: "编程、研究技术问题", keywords: ["技术探索"] },
      { text: "和朋友聚会、参加活动", keywords: ["社交活力"] },
      { text: "参加公益活动、帮助他人", keywords: ["公益服务"] },
    ],
  },
  {
    id: 2,
    question: "你理想的社团氛围是？",
    options: [
      { text: "轻松自由，大家可以自由发挥", keywords: ["创意表达"] },
      { text: "严谨有序，有明确的目标和规划", keywords: ["学术研究"] },
      { text: "活力四射，充满激情和能量", keywords: ["社交活力", "运动健将"] },
      { text: "温馨友爱，像一个大家庭", keywords: ["公益服务"] },
    ],
  },
  {
    id: 3,
    question: "你更希望在社团中获得什么？",
    options: [
      { text: "专业技能的提升", keywords: ["技术探索", "学术研究"] },
      { text: "丰富的人际关系", keywords: ["社交活力"] },
      { text: "实现自我价值，帮助他人", keywords: ["公益服务"] },
      { text: "展示自我才艺的舞台", keywords: ["创意表达"] },
    ],
  },
  {
    id: 4,
    question: "你每周愿意投入多少时间在社团活动上？",
    options: [
      { text: "1-2小时，轻度参与", keywords: ["社交活力"] },
      { text: "3-4小时，适度投入", keywords: ["创意表达", "公益服务"] },
      { text: "5-6小时，积极参与", keywords: ["技术探索", "运动健将"] },
      { text: "7小时以上，深度投入", keywords: ["学术研究"] },
    ],
  },
  {
    id: 5,
    question: "在团队项目中，你通常扮演什么角色？",
    options: [
      { text: "创意策划者，提供创新想法", keywords: ["创意表达"] },
      { text: "技术执行者，解决技术问题", keywords: ["技术探索"] },
      { text: "组织协调者，推动项目进展", keywords: ["社交活力", "公益服务"] },
      { text: "研究分析者，深入挖掘信息", keywords: ["学术研究"] },
    ],
  },
  {
    id: 6,
    question: "你对哪类活动最感兴趣？",
    options: [
      { text: "音乐会、展览、表演等艺术活动", keywords: ["创意表达"] },
      { text: "竞赛、挑战、运动赛事", keywords: ["运动健将", "技术探索"] },
      { text: "公益服务、社区活动", keywords: ["公益服务"] },
      { text: "讲座、研讨会、学术交流", keywords: ["学术研究"] },
    ],
  },
  {
    id: 7,
    question: "你的个人特质更接近哪个描述？",
    options: [
      { text: "富有创造力，喜欢独特的表达方式", keywords: ["创意表达"] },
      { text: "逻辑清晰，喜欢解决复杂问题", keywords: ["技术探索"] },
      { text: "开朗活泼，容易与人打成一片", keywords: ["社交活力"] },
      { text: "有责任感，关注社会公平", keywords: ["公益服务"] },
    ],
  },
  {
    id: 8,
    question: "你最希望毕业后回想起的社团经历是？",
    options: [
      { text: "站在舞台上展示才艺的瞬间", keywords: ["创意表达"] },
      { text: "解决了某个技术难题的成就感", keywords: ["技术探索"] },
      { text: "与来自各地的朋友建立深厚友谊", keywords: ["社交活力"] },
      { text: "为他人或社会带来了实质改变", keywords: ["公益服务"] },
    ],
  },
  {
    id: 9,
    question: "遇到难题时，你的第一反应是？",
    options: [
      { text: "查资料、研究文献，深入分析", keywords: ["学术研究"] },
      { text: "找人商量，集思广益", keywords: ["社交活力"] },
      { text: "动手实验，尝试各种方案", keywords: ["技术探索"] },
      { text: "换个角度，用创意解决", keywords: ["创意表达"] },
    ],
  },
  {
    id: 10,
    question: "你最喜欢的学习方式是？",
    options: [
      { text: "系统学习，打好理论基础", keywords: ["学术研究"] },
      { text: "边做边学，在实践中成长", keywords: ["技术探索", "运动健将"] },
      { text: "跟同伴互相学习，共同进步", keywords: ["社交活力", "公益服务"] },
      { text: "自由探索，发挥个人创造力", keywords: ["创意表达"] },
    ],
  },
  {
    id: 11,
    question: "如果你可以为社团贡献一件事，你会选择？",
    options: [
      { text: "策划一场精彩的演出或展览", keywords: ["创意表达"] },
      { text: "开发一个好用的管理系统", keywords: ["技术探索"] },
      { text: "组织一次大型交流活动", keywords: ["社交活力"] },
      { text: "发起一项有意义的公益项目", keywords: ["公益服务"] },
    ],
  },
  {
    id: 12,
    question: "你平时最欣赏哪类人？",
    options: [
      { text: "有才华、有创造力的艺术家", keywords: ["创意表达"] },
      { text: "技术精湛、能解决问题的工程师", keywords: ["技术探索"] },
      { text: "有领导力、能带动团队的人", keywords: ["社交活力"] },
      { text: "有爱心、为社会默默付出的人", keywords: ["公益服务", "学术研究"] },
    ],
  },
];

export const profileTypes: Record<string, { emoji: string; desc: string }> = {
  创意表达型: { emoji: "🎨", desc: "富有创造力，喜欢艺术和表达，适合文艺类社团" },
  技术探索型: { emoji: "💻", desc: "热爱技术，逻辑思维强，适合技术和学术类社团" },
  社交活力型: { emoji: "🌟", desc: "开朗外向，善于交际，适合各类活动类社团" },
  公益服务型: { emoji: "💝", desc: "有爱心，责任感强，适合公益和服务类社团" },
  学术研究型: { emoji: "📚", desc: "严谨踏实，求知欲强，适合学术和研究类社团" },
  运动健将型: { emoji: "🏃", desc: "热爱运动，充满活力，适合体育运动类社团" },
};

export const mockApplications: Application[] = [
  { id: "a1", clubId: "1", clubName: "星韵合唱团", status: "已通过", appliedAt: "2024-03-10", note: "欢迎加入！" },
  { id: "a2", clubId: "11", clubName: "编程极客社", status: "待审核", appliedAt: "2024-03-15" },
  { id: "a3", clubId: "7", clubName: "青年志愿者协会", status: "已拒绝", appliedAt: "2024-03-08", note: "名额已满，下次优先考虑" },
];

export const adminApplicants: AdminApplicant[] = [
  { id: "u1", name: "李明", club: "编程极客社", status: "待审核", time: "2024-03-15 14:23", profile: "技术探索型" },
  { id: "u2", name: "王小红", club: "星韵合唱团", status: "已通过", time: "2024-03-14 09:12", profile: "创意表达型" },
  { id: "u3", name: "张伟", club: "青年志愿者协会", status: "待审核", time: "2024-03-16 16:45", profile: "公益服务型" },
  { id: "u4", name: "刘洋", club: "篮球俱乐部", status: "已通过", time: "2024-03-13 11:30", profile: "运动健将型" },
  { id: "u5", name: "陈美琳", club: "模拟联合国协会", status: "待审核", time: "2024-03-17 08:55", profile: "学术研究型" },
  { id: "u6", name: "赵子豪", club: "创新创业协会", status: "已拒绝", time: "2024-03-12 15:20", profile: "社交活力型" },
  { id: "u7", name: "林晓雨", club: "街舞嘻哈社", status: "待审核", time: "2024-03-18 10:05", profile: "创意表达型" },
  { id: "u8", name: "孙昊", club: "天文观测协会", status: "已通过", time: "2024-03-11 14:30", profile: "学术研究型" },
];
